name: Deploy Telegram Bot

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Build Docker image
        run: docker build -t telegram_bot .

      - name: Run container with secrets
        run: docker run -d --name my_bot -e BOT_TOKEN=${{ secrets.BOT_TOKEN }} -e DATABASE=users.db telegram_bot
